services:
  mongo:
    image: mongo:6
    container_name: CAA-mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: algorithm_analysis
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: CAA-backend
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/algorithm_analysis
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: CAA-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

volumes:
  mongo-data:
