services:
  mongo:
    image: mongo:6
    container_name: CAA-mongo-test
    restart: always
    environment:
      MONGO_INITDB_DATABASE: algorithm_analysis
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      dockerfile: Dockerfile
    container_name: CAA-backend-test
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/algorithm_analysis
    ports:
      - "8080:8080"

volumes:
  mongo-data: